# Generated by Django 3.1.4 on 2020-12-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
