# Generated by Django 3.1.4 on 2020-12-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_blog', '0008_auto_20201222_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200, null=True, unique=True),
        ),
    ]
