# Generated by Django 3.1.4 on 2020-12-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_blog', '0012_auto_20201222_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-user_name']},
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
