# Generated by Django 3.1.4 on 2020-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_blog', '0016_auto_20201225_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
