# Generated by Django 3.1.4 on 2020-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_blog', '0017_auto_20201225_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
